/*
    Generated by Atomist on 05 07 2016 
*/
package com.maxgrip.streamplus.riskcalculator;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class RiskCalculatorApplication {

    public static void main(String[] args) {
        SpringApplication.run(RiskCalculatorApplication.class, args);
    }
}
